runtime: nodejs20  
service: backend  

basic_scaling:
  max_instances: 10  
  idle_timeout: 10m  

env_variables:
  NODE_ENV: 'production'
  # PORT: 5001
  FIREBASE_PROJECT_ID: fashionthief-a6f61
  FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@fashionthief-a6f61.iam.gserviceaccount.com
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDbzuht4srq00b\nQM+WWG7LXmLHJ7lbYNNFKLikscVBOcbs9ArAxFgsf4Lf60VXtLQ+qtkRiI5k4Bur\nrzykKuY4eRzvWjQWPvf8VW71c+abDbBSRSL2AYm+Am6RgL+dZq/tz2crsuLSDKJT\ne4F1oa5w+lYt/EXLkdkATZIzH78x+tqwYcWqYrlmOCjSN+XbQ6ekzfOOPy5XDtHc\n77NfPwQhvT7HTseGnwp+BXatiB4VU+n4Bee24Z7N4jceP8BtliqJG/IvJ9qm5nNf\nbahy5NJFsU3frhI3m2h729nriorYs8WKgqspeU7le/ImMyd6yPXoS2S7XcoJPpfl\njWFx//+vAgMBAAECggEAAogEnzXtiUYOs/Ap/kc0EVlExBYCx4Nr3dIhO8N0Kg0V\ncIyrW88tWnyMM53dS8ycLd/33QeZF2FV9bWkBeByXr/imwdmRshPmXA+bsPb7MLa\nez1fAWgP3rKNTrigVY9RFK5el1hG9UrD9BGgA5yISoDaoTJ/U2cALK+Qwx6ylqfo\nbUA+7L4ubqZfiio0b7PLecr0u69/GzdOPHALkhcNElrpwI8tbV0y+Dw9tgDxtYJ2\nwNlRV/Ma3Jv+suPHxiHcXnlGECgPWgWjXWbju7lgocO3LLW5LD7GfAY1ubQG2Rzf\nC1WztdSX36O78BzL/fMwwlPqXFQFSb9wq5PPMPxBQQKBgQDlRQwTUIWmkQNPT/k1\n8hozztZlvKhD7AJk8ZkL0Lrh0OTnNQo9WGVFz1HxJWNpbCqn9dTS/ef7IwAb+Hjl\nVxb3kIOMq2T1worM9zdjOd6V9vi5zlpO4CblhR9DUJ1PgBSxtI5WfS2ZRHa6X1yl\nGxQcvK+T+9ynWHCd3x1UTldTwQKBgQDaOFCq5Qn3LrGIXxAx7hzY+1SqG20KZtgU\nZvJ9pidbcyZ9pCvL15/OjpA8HHL0p55sbbqpB6RSTK5+3VK9vIf4o1HHiFq4n4v9\nn6KvMe4riSHd+mby8G+HPNBfh8MebEzSb7toFrmp8F3OizINfTKd1S3QTVHnEtSJ\n5JYxCVJvbwKBgDu+kHUACLPtGgWy+2gZXMafYbNFRDve5ojThGRV0j1CKEQvyClQ\nPaPBcML8UTmJnFwEbZ9F1wvUhRTE3Qw2c5+zovQnPbnlJjJfQamzzNMbdplEsrfX\nJYut8wWhnjy3Ta05NdZH7HgCJUZPz16e/dC3QrG3cjqRi1c4avYrLAqBAoGAFELo\nUoXDoBzIxRW2hjxKl2b2nHjBbhbQd0x7tWjo/Je7eiz1GA8kOmSIRdyKW+b4Ua76\nhtk7y5xtE0Bvf0hzA4X+gN1LNxsxP1JEI6oqKAaqi1bFmkbyxAbEfio31qpNk7hm\nGSsLABleTGAmPJRkT71MbKvRL/hSnZ8IxvLLoacCgYEAsOg8HkMMJROM9liX/NQC\nztuP11R3UIDipg7IQqPacIfRRZZqUOXrCFqAYSA6M2NTD/7BOAHD+V37H9AJpaOQ\nZFI3cRbIxmVZ3Mh54GO0xrRqm7Xm5jn/ebZwDE73OpWQq7Tf2ZSavjDEXUdHu2T1\nIp3Oq6w05QHo/HqDMRH8JGI=\n-----END PRIVATE KEY-----\n"
  FIREBASE_STORAGE_BUCKET: fashionthief-a6f61.firebasestorage.app
  GEMINI_API_KEY: AIzaSyDqTkWL0CVFcnR6oqnIE9Pe1X7TNIXxLA8
  GOOGLE_APPLICATION_CREDENTIALS: ./services/creds.json

network:
  session_affinity: true 
  instance_tag: backend
  forwarded_ports:
    - 8080

handlers:
  - url: /.*
    secure: always
    script: auto

resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 10

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
